spring:
  datasource:
    url: ${MANYAK_DB_URL:jdbc:postgresql://localhost:5432/manyak}
    username: ${MANYAK_DB_USERNAME:manyak}
    password: ${MANYAK_DB_PASSWORD:manyak}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
