package com.knk.manyak.global.config

import io.micrometer.observation.Observation
import io.micrometer.observation.ObservationHandler
import io.micrometer.observation.ObservationRegistry
import net.ttddyy.observation.boot.autoconfigure.DataSourceObservationAutoConfiguration
import net.ttddyy.observation.boot.autoconfigure.JdbcProperties
import net.ttddyy.observation.tracing.QueryContext
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.springframework.boot.autoconfigure.AutoConfigurations
import org.springframework.boot.env.YamlPropertySourceLoader
import org.springframework.boot.micrometer.observation.autoconfigure.ObservationAutoConfiguration
import org.springframework.boot.test.context.runner.ApplicationContextRunner
import org.springframework.core.env.StandardEnvironment
import org.springframework.core.io.ClassPathResource
import org.springframework.jdbc.datasource.DriverManagerDataSource
import java.sql.Statement
import javax.sql.DataSource

class JdbcQueryObservationTests {
    @Test
    fun `실제 설정은 query만 남기며 SQL과 요청 부모를 보존하고 파라미터는 숨긴다`() {
        val captured = mutableListOf<Observation.Context>()
        val handler = object : ObservationHandler<Observation.Context> {
            override fun supportsContext(context: Observation.Context) = true
            override fun onStop(context: Observation.Context) { captured.add(context) }
        }
        ApplicationContextRunner()
            .withInitializer { context ->
                val sources = context.environment.propertySources
                sources.remove(StandardEnvironment.SYSTEM_ENVIRONMENT_PROPERTY_SOURCE_NAME)
                sources.remove(StandardEnvironment.SYSTEM_PROPERTIES_PROPERTY_SOURCE_NAME)
                YamlPropertySourceLoader().load("application", ClassPathResource("application.yml"))
                    .forEach(sources::addLast)
            }
            .withConfiguration(AutoConfigurations.of(
                ObservationAutoConfiguration::class.java,
                DataSourceObservationAutoConfiguration::class.java,
            ))
            .withUserConfiguration(JdbcQuerySpanNaming::class.java, TracingNoiseFilter::class.java)
            .withBean(ObservationHandler::class.java, { handler })
            .withBean(DataSource::class.java, { DriverManagerDataSource("jdbc:h2:mem:jdbcTidy", "sa", "") })
            .run { context ->
                assertThat(context).hasNotFailed()
                assertThat(context.getBean(JdbcProperties::class.java).includes)
                    .containsExactly(JdbcProperties.TraceType.QUERY)
                val registry = context.getBean(ObservationRegistry::class.java)
                val dataSource = context.getBean(DataSource::class.java)
                val request = Observation.start("http.server.requests", registry)
                try {
                    request.openScope().use {
                        dataSource.connection.use { connection ->
                            connection.createStatement().use {
                                it.executeUpdate("create table stories (id bigint generated by default as identity, content varchar(100))")
                            }
                            captured.clear()
                            connection.prepareStatement("insert into stories (content) values (?)", Statement.RETURN_GENERATED_KEYS).use {
                                it.setString(1, "private-value")
                                it.executeUpdate()
                                it.generatedKeys.use { keys -> assertThat(keys.next()).isTrue() }
                            }
                            connection.prepareStatement("select content from stories where content=?").use {
                                it.setString(1, "private-value")
                                it.executeQuery().use { rows -> assertThat(rows.next()).isTrue() }
                            }
                        }
                    }
                    assertThat(captured.map { it.name }).containsExactly("jdbc.query", "jdbc.query")
                    assertThat(captured.map { it.contextualName }).containsExactly("INSERT stories", "SELECT stories")
                    captured.forEach {
                        assertThat(it.parentObservation).isSameAs(request)
                        assertThat((it as QueryContext).params).isEmpty()
                        assertThat(it.highCardinalityKeyValues.find { keyValue -> keyValue.key == "jdbc.query[0]" }?.value).contains("?")
                        assertThat(it.highCardinalityKeyValues.toString()).doesNotContain("private-value")
                    }
                    captured.clear()
                    // 요청 밖 JDBC와 걸러진 예약 작업 아래 JDBC는 여전히 생성하지 않는다.
                    fun queryOutsideRequest() {
                        dataSource.connection.use { connection ->
                            connection.createStatement().use { it.executeQuery("select 1").close() }
                        }
                    }
                    queryOutsideRequest()
                    val scheduled = Observation.start("tasks.scheduled.execution", registry)
                    try {
                        scheduled.openScope().use { queryOutsideRequest() }
                    } finally {
                        scheduled.stop()
                    }
                    assertThat(captured).isEmpty()
                } finally {
                    request.stop()
                }
            }
    }
}
