CREATE TABLE push_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id varchar(255) NOT NULL UNIQUE,
    payload jsonb NOT NULL,
    status varchar(16) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'PUBLISHED', 'FAILED')),
    attempts integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    published_at timestamptz
);
CREATE INDEX idx_push_outbox_pending ON push_outbox (next_attempt_at) WHERE status = 'PENDING';
