ALTER TABLE stories ADD COLUMN protagonist_name TEXT;
ALTER TABLE stories ADD CONSTRAINT ck_stories_protagonist_name_length
    CHECK (protagonist_name IS NULL OR char_length(protagonist_name) BETWEEN 1 AND 30);

CREATE TABLE user_personas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    name TEXT NOT NULL CHECK (char_length(name) BETWEEN 1 AND 20),
    description TEXT NOT NULL CHECK (char_length(description) BETWEEN 1 AND 1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_user_personas_active_user_created ON user_personas(user_id, created_at DESC, id DESC)
    WHERE deleted_at IS NULL;

ALTER TABLE story_chats ADD COLUMN persona_name_snapshot TEXT;
ALTER TABLE story_chats ADD COLUMN persona_description_snapshot TEXT;
ALTER TABLE story_chats ADD CONSTRAINT ck_story_chats_persona_pair
    CHECK ((persona_name_snapshot IS NULL) = (persona_description_snapshot IS NULL));
ALTER TABLE story_chats ADD CONSTRAINT ck_story_chats_persona_name_length
    CHECK (persona_name_snapshot IS NULL OR char_length(persona_name_snapshot) BETWEEN 1 AND 20);
ALTER TABLE story_chats ADD CONSTRAINT ck_story_chats_persona_description_length
    CHECK (persona_description_snapshot IS NULL OR char_length(persona_description_snapshot) BETWEEN 1 AND 1000);
